# Generated by Django 4.2.4 on 2024-03-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=30, verbose_name='نام محصول')),
                ('category', models.CharField(max_length=50, verbose_name='دسته بندی')),
                ('gheymat', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('off', models.IntegerField(default=1, verbose_name='تخفیف')),
                ('aks', models.ImageField(upload_to='shop/static/shop/assets/images/aks', verbose_name='عکس')),
                ('tosif', models.TextField(verbose_name='توصیف')),
                ('noe', models.IntegerField(default=1)),
            ],
        ),
    ]
