# Generated by Django 4.2.4 on 2024-03-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pcategory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pcategory',
        ),
    ]
