# Generated by Django 5.0.3 on 2024-03-12 04:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_pcategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="pcategory",
        ),
    ]
