# Generated by Django 5.0.3 on 2024-03-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_category_product_pcategory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pcategory",
        ),
        migrations.AddField(
            model_name="product",
            name="pcategory",
            field=models.ManyToManyField(to="api.pcategory", verbose_name="دسته بندی"),
        ),
    ]
