# Generated by Django 4.2.4 on 2023-09-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsool',
            name='aks',
            field=models.ImageField(upload_to='aks'),
        ),
    ]
