# Generated by Django 4.2.4 on 2023-09-16 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_mahsool_aks'),
    ]

    operations = [
        migrations.CreateModel(
            name='akss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akss', models.ImageField(upload_to='img')),
                ('related_mahsool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='shop.mahsool')),
            ],
        ),
    ]
