# Generated by Django 4.2.4 on 2023-09-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_akss'),
    ]

    operations = [
        migrations.AddField(
            model_name='akss',
            name='noe',
            field=models.IntegerField(default=1),
        ),
    ]
