# Generated by Django 4.2.4 on 2023-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_akss_noe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akss',
            name='akss',
            field=models.ImageField(upload_to='shop/static/shop/assets/images/img'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='aks',
            field=models.ImageField(upload_to='shop/static/shop/assets/images/aks'),
        ),
    ]
