# Generated by Django 4.2.4 on 2024-01-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_akss_akss_alter_mahsool_aks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsool',
            name='onvan',
            field=models.CharField(choices=[('l', 'لپ تاپ'), ('p', 'پرینتر و اسکنر'), ('j', 'لوازم جانبی')], max_length=30),
        ),
    ]
