# Generated by Django 4.2.4 on 2024-01-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_mahsool_onvan'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsool',
            name='category',
            field=models.CharField(choices=[('l', 'لپ تاپ'), ('p', 'پرینتر و اسکنر'), ('j', 'لوازم جانبی')], default='l', max_length=30),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='onvan',
            field=models.CharField(max_length=30),
        ),
    ]
