# Generated by Django 4.2.4 on 2024-01-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_mahsool_category_alter_mahsool_onvan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsool',
            name='category',
            field=models.CharField(choices=[('l', 'لپ تاپ'), ('p', 'پرینتر و اسکنر'), ('j', 'لوازم جانبی')], default='l', max_length=30, null=True),
        ),
    ]
