# Generated by Django 4.2.4 on 2024-01-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_mahsool_onvan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsool',
            name='onvan',
            field=models.CharField(max_length=30),
        ),
    ]
