# Generated by Django 4.2.4 on 2024-02-10 14:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_mahsool_onvan'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30, verbose_name='نام')),
                ('lastname', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('username', models.CharField(max_length=30, verbose_name=' نام کاربری')),
                ('password', models.CharField(max_length=30, verbose_name='رمز عبور')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='faktor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('totalprice', models.DecimalField(decimal_places=0, max_digits=10)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.client')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='text',
            field=models.CharField(max_length=500, verbose_name='متن'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='aks',
            field=models.ImageField(upload_to='shop/static/shop/assets/images/aks', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='category',
            field=models.CharField(choices=[('l', 'لپ تاپ'), ('p', 'پرینتر و اسکنر'), ('j', 'لوازم جانبی')], default='l', max_length=30, null=True, verbose_name='دسته'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='gheymat',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='off',
            field=models.IntegerField(default=1, verbose_name='تخفیف'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='onvan',
            field=models.CharField(max_length=30, verbose_name='نام محصول'),
        ),
        migrations.AlterField(
            model_name='mahsool',
            name='tosif',
            field=models.TextField(verbose_name='توصیف'),
        ),
        migrations.CreateModel(
            name='sabad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt', models.IntegerField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.client')),
                ('mahsool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.mahsool')),
            ],
        ),
        migrations.CreateModel(
            name='faktor_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qnt', models.IntegerField()),
                ('faktor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.faktor')),
                ('mahsool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.mahsool')),
            ],
        ),
    ]
