# Generated by Django 4.2.4 on 2024-02-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_client_faktor_alter_contact_email_alter_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onvan', models.CharField(max_length=30, verbose_name='دسته')),
            ],
        ),
    ]
