# Generated by Django 4.2.4 on 2024-02-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_remove_mahsool_category_mahsool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsool',
            name='is_special',
            field=models.BooleanField(null=True, verbose_name=' فروش ویژه'),
        ),
        migrations.AddField(
            model_name='mahsool',
            name='special_price',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True, verbose_name=' قیمت ویژه'),
        ),
    ]
