# Generated by Django 4.2.4 on 2024-03-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_mahsool_is_special'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mahsool',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='faktor_details',
            old_name='mahsool',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='sabad',
            old_name='mahsool',
            new_name='product',
        ),
    ]
