# Generated by Django 5.0.3 on 2024-03-11 21:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0018_rename_mahsool_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="category",
            new_name="pcategory",
        ),
    ]
