# Generated by Django 5.0.3 on 2024-03-12 03:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0019_rename_category_product_pcategory"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={},
        ),
    ]
