# Generated by Django 5.0.3 on 2024-03-12 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0021_alter_client_options_remove_product_pcategory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="pcategory",
        ),
        migrations.AddField(
            model_name="product",
            name="pcategory",
            field=models.ManyToManyField(to="shop.category"),
        ),
    ]
