# Generated by Django 5.0.3 on 2024-03-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0023_rename_pcategory_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="faktor",
            name="ispaid",
            field=models.BooleanField(default=False),
        ),
    ]
