# Generated by Django 5.0.3 on 2024-03-13 02:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0024_faktor_ispaid"),
    ]

    operations = [
        migrations.AddField(
            model_name="faktor_details",
            name="sent",
            field=models.BooleanField(default=False),
        ),
    ]
